#:schema = "https://yazi-rs.github.io/schemas/yazi.json"
# For yazi settings.
[manager]
sort_by        = "natural"
sort_sensitive = true
linemode       = "size_and_mtime"
show_hidden    = true

[preview]
max_width     = 1200
max_height    = 1200
image_quality = 90

# For plugins.
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
