[tools]
usage = "latest"
ruby = "latest"
neovim = "latest"
ktlint = "latest"
hadolint = "latest"
golangci-lint = "latest"
flutter = "latest"
dotnet = "latest"
dart = "latest"
bun = "latest"
deno = "latest"
grpcurl = "latest"
kind = "latest"
kotlin = "latest"
tfsec = "latest"
rye = "latest"
ruff = "latest"
jq = "latest"
yq = "latest"

[settings]
python_compile = true
