#:schema = "https://raw.githubusercontent.com/mise-app/mise/main/schemas/config.schema.json"
[tools]
actionlint                                 = "latest"
"aqua:mrtazz/checkmake"                    = "latest"
biome                                      = "latest"
buf                                        = "latest"
bun                                        = "latest"
"cargo:cargo-binstall"                     = "latest"
"cargo:cargo-cache"                        = "latest"
"cargo:cargo-update"                       = "latest"
"cargo:cargo-watch"                        = "latest"
"cargo:jaq"                                = "latest"
cmake                                      = "latest"
dart                                       = "latest"
delta                                      = "latest"
deno                                       = "latest"
"dotnet:csharpier"                         = "latest"
"dotnet:dotnet-aspnet-codegenerator"       = "latest"
"dotnet:dotnet-ef"                         = "latest"
"dotnet:dotnet-outdated-tool"              = "latest"
"dotnet:dotnet-reportgenerator-globaltool" = "latest"
"dotnet:linux-dev-certs"                   = "latest"
"dotnet:powershell"                        = "latest"
"dotnet:roslynator.dotnet.cli"             = "latest"
dprint                                     = "latest"
eza                                        = "latest"
fd                                         = "latest"
flutter                                    = "latest"
fzf                                        = "latest"
github-cli                                 = "latest"
gitui                                      = "latest"
go                                         = "latest"
"go:github.com/go-delve/delve/cmd/dlv"     = "latest"
golangci-lint                              = "latest"
gradle                                     = "latest"
grpcurl                                    = "latest"
hadolint                                   = "latest"
jq                                         = "latest"
jwt                                        = "latest"
jwtui                                      = "latest"
kind                                       = "latest"
kotlin                                     = "latest"
ktlint                                     = "latest"
lefthook                                   = "latest"
markdownlint-cli2                          = "latest"
maven                                      = "latest"
neovim                                     = "latest"
node                                       = "lts"
"npm:@antfu/ni"                            = "latest"
"npm:@devcontainers/cli"                   = "latest"
"npm:editorconfig-checker"                 = "latest"
"npm:neovim"                               = "latest"
"npm:sass"                                 = "latest"
"npm:yarn"                                 = "latest"
php                                        = "8.3.9"
"pipx:argcomplete"                         = "latest"
"pipx:cmakelang"                           = "latest"
"pipx:codespell"                           = "latest"
"pipx:cpplint"                             = "latest"
"pipx:debugpy"                             = "latest"
"pipx:flawfinder"                          = "latest"
"pipx:pipx"                                = "latest"
"pipx:pytest"                              = "latest"
"pipx:python-build"                        = "latest"
"pipx:sqlfluff"                            = "latest"
pnpm                                       = "latest"
protoc                                     = "latest"
ripgrep                                    = "latest"
ruby                                       = "latest"
ruff                                       = "latest"
rye                                        = "latest"
shellcheck                                 = "latest"
shfmt                                      = "latest"
stylua                                     = "latest"
taplo                                      = "latest"
terraform                                  = "latest"
tfsec                                      = "latest"
tmux                                       = "latest"
tree-sitter                                = "latest"
usage                                      = "latest"
uv                                         = "latest"
yamllint                                   = "latest"
yazi                                       = "latest"
yq                                         = "latest"
zoxide                                     = "latest"

[settings]
experimental                  = true
python_compile                = true
fetch_remote_versions_timeout = "60s"
http_timeout                  = "60s"
