[tools]
usage = "latest"
ruby = "latest"
neovim = "latest"
ktlint = "latest"
hadolint = "latest"
golangci-lint = "latest"
flutter = "latest"
dotnet = "latest"
dart = "latest"
poetry = "latest"
bun = "latest"
deno = "latest"
grpcurl = "latest"
kind = "latest"
kotlin = "latest"
tfsec = "latest"
rye = "latest"

[settings]
python_compile = true
