[tools]
usage = "latest"
ruby = "latest"
neovim = "stable"
ktlint = "latest"
hadolint = "latest"
golangci-lint = "latest"
flutter = "latest"
dotnet = "latest"
dart = "latest"
actionlint = "latest"
tfsec = "latest"
poetry = "latest"
