[tools]
biome = "latest"
bun = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-update" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:jaq" = "latest"
dart = "latest"
deno = "latest"
dotnet = "latest"
"dotnet:dotnet-aspnet-codegenerator" = "latest"
"dotnet:dotnet-ef" = "latest"
"dotnet:dotnet-outdated-tool" = "latest"
"dotnet:dotnet-reportgenerator-globaltool" = "latest"
"dotnet:linux-dev-certs" = "latest"
"dotnet:powershell" = "latest"
"dotnet:roslynator.dotnet.cli" = "latest"
flutter = "latest"
"gem:bundler" = "latest"
golangci-lint = "latest"
grpcurl = "latest"
hadolint = "latest"
jq = "latest"
kind = "latest"
kotlin = "latest"
ktlint = "latest"
markdownlint-cli2 = "latest"
neovim = "latest"
npm = "latest"
php = "8.3.9"
pnpm = "latest"
ruby = "latest"
ruff = "latest"
rye = "latest"
tfsec = "latest"
usage = "latest"
uv = "latest"
yamllint = "latest"
yq = "latest"

[settings]
experimental = true
python_compile = true

